default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: make-lint-code
        name: make-lint-code
        entry: bash -c 'make lint'
        language: system
        types:
          - python
        pass_filenames: false
